baseURL = "/"
languageCode = "en-us"
title = "Wandering Quandaries"
theme = "kube"
description = "Bytes inspired by backcountry grit."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Joshua Roppo" # add your company name
  github = "Ropes" # add your github profile name
  twitter = "@joshroppo" # add your twitter profile
  email = ""

[[menu.main]]
    name = "Blog"
    weight = 10 
    url = "/blog/"
[[menu.main]]
    name = "Backcountry"
    weight = 100
    url = "/backcountry/"
[[menu.main]]
    name = "Photography"
    weight = 200
    url = "/faq/"
